<?php
/**
 * Created by PhpStorm.
 * User: chunmao
 * Date: 2016/8/15 0015
 * Time: 下午 15:24
 */

namespace common\widgets;
use yii\bootstrap\Modal;
use yii\bootstrap\Widget;
use yii\web\HttpException;


/**
 * 下载进度条，需要外部配合使用
 * Class UploadProgress
 * @package common\widgets
 */
class UploadProgress extends Widget
{
    public $title = '上传进度';
    public $id = 'modalUploadProgress';
    public $idPrefix = 'upload_';

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        // 注册js
        $this->view->registerJsFile('@web/js/upload/upload.js');
        $this->view->registerJs(<<<END
            $(".m-upload-btn").click(function(){
                //alert($(this).siblings(".file-input").attr("id"))
                // $(this).siblings(".file-input").click()
            });
END
);

        $modal = Modal::begin([
            'header' => "<h2>$this->title</h2>",
            'toggleButton' => false,
            'id' => $this->id,
            //'size' => Modal::SIZE_LARGE,
            'clientOptions' => ['backdrop' => 'static', 'keyboard' => false], // 禁止点击空白区域和esc键关闭
        ]);
        echo '<div id="progress_info">
			<div class="progress">
				<div class="progress-bar"  id="upload_progress">
				</div>
			</div>
                        <div id="upload_progress_percent">&nbsp;</div>
                        <div class="clear_both"></div>
                        <div>
                            <div id="upload_speed">&nbsp;</div>
                            <div id="upload_remaining">&nbsp;</div>
                            <div id="upload_b_transfered">&nbsp;</div>
                            <div class="clear_both"></div>
                        </div>
                        <div id="upload_response"></div>
                    </div>
';

        Modal::end();

    }

    public static function uploadImageFileField($form, $uploadModel, $fieldName, $label, $labelOptions = [], $maxWidth = '100px', $showFileSize = true)
    {
        $result = '';
        $inputField = $form->field($uploadModel, $fieldName)
                ->fileInput([
                    'multiple' => false, 'accept' => 'image/png, image/jpeg', 'class' => 'file-input hidden',
                    'id' => 'upfile_' . $fieldName,
                    'onchange' => "fileSelected('upfile_$fieldName', 'img_$fieldName', 'label_$fieldName');return false;"
                ])
                ->label($label, $labelOptions);
        $uploadButton = '<a href="javascript:;" class="m-upload-btn" onclick="$(this).siblings(\'.file-input\').click();">选择图片</a>';
        $inputField->template = "{label}\n{input}{$uploadButton}\n{hint}\n{error}";
        $result .= $inputField;
        $result .= "<img id='img_$fieldName' class='input-image-file-view' style='max-width:$maxWidth;cursor:pointer;' data-target='#view-img-{$fieldName}' data-toggle='modal' src='".$uploadModel->imageFile."'>";

        if($showFileSize) {
            $result .= "<div style=\"margin-bottom:10px;\"><label class='input-image-file-size' id='label_$fieldName'></label></div>";
        } else {
            $result .="<div>&nbsp;</div>";
        }

        //构建图片预览弹层@macro
        self::buildViewModal("view-img-{$fieldName}", $fieldName, $uploadModel->imageFile);

        return $result;
        //return '<table><tr><td>' . $form->field($uploadModel, $fieldName)->fileInput(['multiple' => false, 'accept' => 'image/png, image/jpeg',
        //    'id' => 'upfile_' . $fieldName,  'onchange' => "fileSelected('upfile_$fieldName', 'img_$fieldName', 'label_$fieldName');"])->label($label)
        //    . "</td><td align='center'><img id='img_$fieldName' style='max-width:$maxWidth'><br><label id='label_$fieldName'></label></td></tr></table>";
    }

    //图片预览弹层@macro
    public static function buildViewModal($modalLayerId, $imgTagId, $imgUrl = '', $header = '图片预览', $size = Modal::SIZE_LARGE){
        $modal = Modal::begin([
            'id' => $modalLayerId,
            'header' => $header,
            'size' => $size,
        ]);
        echo "<div class='text-center'><img src='{$imgUrl}' style='max-width:870px;' id='view_img_{$imgTagId}' /></div>";
        Modal::end();
        return $modal;
    }
}